### PR TITLE
CODE RUB: Make Lab Service Pretty ❤️

### PR DESCRIPTION
**Pull request by hassanhabib**
Here's some updates to ensure our code is very readable and easy to understand:

1. I abstracted away some of the work we needed to do to map `ExternalLab` to `Lab` components.
2. I flattened out our exception handling to ensure cognitive consistency
3. I changed `ReturningLabFunction` for the exception delegate to `ReturningLabsFunction` (variable name changed as well)
4. Move `LabService` and `ILabService` under Labs namespace/folder.

### CODE REVIEW

**Review by ShriHumrudha — COMMENTED** [review]
As part of following 'The Standard', a couple of observations.
1. The scope of code is beyond the foundation layer
2. These files should be under 'LabServices' folder.

**Comment by hassanhabib** [comment]
> As part of following 'The Standard', a couple of observations.
> 
> 1. The scope of code is beyond the foundation layer
> 2. These files should be under 'LabServices' folder.

@ShriHumrudha please elaborate on the scope being beyond the foundations layer.

**Comment by ShriHumrudha** [comment]
> > As part of following 'The Standard', a couple of observations.
> > 
> > 1. The scope of code is beyond the foundation layer
> > 2. These files should be under 'LabServices' folder.
> 
> @ShriHumrudha please elaborate on the scope being beyond the foundations layer.
> 
> Great catch on the Labs namespace, thank you.

As there is code for transformation, I was more inclining to place it in a processing service than a foundation service.

**Comment by hassanhabib** [comment]
> > > As part of following 'The Standard', a couple of observations.
> > > 
> > > 1. The scope of code is beyond the foundation layer
> > > 2. These files should be under 'LabServices' folder.
> > 
> > 
> > @ShriHumrudha please elaborate on the scope being beyond the foundations layer.
> > Great catch on the Labs namespace, thank you.
> 
> As there is code for transformation, I was more inclining to place it in a processing service than a foundation service.

Processing services don't transfer external models to local. That's the Foundation services role to map and abstract away any external or native models to local models.

Here's our definition of Foundation Services:
_The second responsibility for a foundation service is to play the role of a mapper both ways between local models and non-local models. For instance, if you are leveraging an email service that provides it's own SDKs to integrate with, and your brokers are already wrapping and exposing the APIs for that service, your foundation service is required to map the inputs and outputs of the broker methods into local models. the same situation and more commonly between native non-local exceptions such as the ones we mentioned above with the dependency validation situation, the same aspect applies to just dependency errors or service errors as we will discuss shortly._

[[The Standard: Mapping 2.1.3.2]](https://github.com/hassanhabib/The-Standard/blob/master/2.%20Services/2.1%20Foundations/2.1%20Foundations.md#2132-mapping)

**Review by AndrewMcClelland — APPROVED** [review]

**Pull request merged**
